### ISSUE TITLE
19.9.2023 22:06:47 [Server Error] Item with code shepherdmod:shepherdstaff has defined an item class ShepherdStaff, but no such class registered. Will ignore.

### ISSUE THREAD

**Issue by CipherArrow** [JanLopata/shepherd-mod#3]
According to: https://wiki.vintagestory.at/index.php/Modding:Block_Classes
And following the description on how to use Class:"", in its first paragraph, the Class:"" is described in a way that tells me that you should not utilize Class:ShepherdStaff", in your mod simply because there is not any C# class for it to reference information from in the mod, nor in the https://github.com/anegostudios/vssurvivalmod/ portion of Vintage Story.

This is why I keep getting the error spam every time a world is rebooted/started:
19.9.2023 22:06:47 [Server Error] Item with code shepherdmod:shepherdstaff has defined an item class ShepherdStaff, but no such class registered. Will ignore.

Can this be removed and your mod safely work without it?

**Comment by JanLopata** [comment]
Thank you for the bug report.

> Can this be removed and your mod safely work without it?

Yes, since there is no code yet in the mod, the class field can be removed from the item definition.

**Comment by JanLopata** [comment]
Solved in `release-1.0.2`.
